# Use Dockerized infrastructure
sudo: false

# Use node_js environnement
language: node_js
node_js:
  - "6.9.1"

# Cache Gcloud SDK between commands
cache:
  yarn: true
  directories:
  - "$HOME/google-cloud-sdk/"

env:
  global:


install:
  - npm install

script:
  - npm test

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update

  # use the decrypted service account credentials to authenticate the command line tool
  # get the encrypted variable names from travis cli: https://docs.travis-ci.com/user/encrypting-files/
  - openssl aes-256-cbc -K $encrypted_e82afbcd63e2_key -iv $encrypted_e82afbcd63e2_iv -in gcloud-service-key.json.enc -out gcloud-service-key.json -d
  - gcloud auth activate-service-account --key-file gcloud-service-key.json
  #ADD YOUR PROJECT ID HERE -- this can be found on the On the Google Cloud Platform Dahsboard under 'Project info'
  - gcloud config set project r-spacex-ai

deploy:
  - provider: script
    script:
      # change FUNCTION_NAME PROJECT and REPO to the values from the cloud console: https://console.cloud.google.com/code/develop. Note function name is from your main file, usualy index.js, the main function exports.FUNCTION_NAME
      - gcloud --quiet beta functions deploy SpaceXFulfillment --source https://source.developers.google.com/projects/r-spacex-ai/repos/r-SpaceX-AI-google-source-repo/moveable-aliases/master --trigger-http
      - gcloud --quiet beta functions call SpaceXFulfillment --data '{"id":"4a95aaa0-bcaf-4c25-8339-d7faa2f68ae8","timestamp":"2017-11-19T18:36:13.96Z","lang":"en","result":{"source":"agent","resolvedQuery":"when was the last launch failure?","speech":"","action":"get.launchInformation","actionIncomplete":false,"parameters":{"LaunchPads":"","LaunchTemporal":"last","MissionOutcome":"false","LaunchQueryParams":"launch_date_local","LaunchOrdinal":"","Vehicles":""},"contexts":[{"name":"information-given","parameters":{"LaunchTemporal.original":"last","LaunchPads":"","LaunchOrdinal.original":"","Vehicles.original":"","MissionOutcome":"false","LaunchTemporal":"last","LaunchQueryParams":"launch_date_local","MissionOutcome.original":"launch failure","LaunchOrdinal":"","LaunchQueryParams.original":"When was","LaunchPads.original":"","Vehicles":""},"lifespan":5},{"name":"global","parameters":{"LaunchTemporal.original":"last","LaunchPads":"","LaunchOrdinal.original":"","Vehicles.original":"","MissionOutcome":"false","LaunchTemporal":"last","LaunchQueryParams":"launch_date_local","MissionOutcome.original":"launch failure","LaunchOrdinal":"","LaunchQueryParams.original":"When was","LaunchPads.original":"","Vehicles":""},"lifespan":98},{"name":"defaultwelcomeintent-followup","parameters":{"LaunchTemporal.original":"last","LaunchPads":"","LaunchOrdinal.original":"","Vehicles.original":"","MissionOutcome":"false","LaunchTemporal":"last","LaunchQueryParams":"launch_date_local","MissionOutcome.original":"launch failure","LaunchOrdinal":"","LaunchQueryParams.original":"When was","LaunchPads.original":"","Vehicles":""},"lifespan":0},{"name":"welcome","parameters":{"LaunchTemporal.original":"last","LaunchPads":"","LaunchOrdinal.original":"","Vehicles.original":"","MissionOutcome":"false","LaunchTemporal":"last","LaunchQueryParams":"launch_date_local","MissionOutcome.original":"launch failure","LaunchOrdinal":"","LaunchQueryParams.original":"When was","LaunchPads.original":"","Vehicles":""},"lifespan":3},{"name":"launches","parameters":{"LaunchTemporal.original":"last","LaunchPads":"","LaunchOrdinal.original":"","Vehicles.original":"","MissionOutcome":"false","LaunchTemporal":"last","LaunchQueryParams":"launch_date_local","MissionOutcome.original":"launch failure","LaunchOrdinal":"","LaunchQueryParams.original":"When was","LaunchPads.original":"","Vehicles":""},"lifespan":5}],"metadata":{"intentId":"a2ee538a-1ab4-454e-9ce8-d82521efffe3","webhookUsed":"true","webhookForSlotFillingUsed":"false","intentName":"launchInformation"},"fulfillment":{"speech":"","messages":[{"type":0,"platform":"slack","speech":"slack text response"},{"type":0,"speech":""}]},"score":1},"status":{"code":200,"errorType":"success","webhookTimedOut":false},"sessionId":"8d6f0e34-8e72-41e2-9f13-9cff876aadd4"}'
    skip_cleanup: true
    on:
      branch: master
