# Use Dockerized infrastructure
sudo: false

# Use node_js environnement
language: node_js
node_js:
  - "6.9.1"

# Cache Gcloud SDK between commands
cache:
  yarn: true
  directories:
  - "$HOME/google-cloud-sdk/"

env:
  global:


install:
  - npm install

script:
  - npm test

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update

  # use the decrypted service account credentials to authenticate the command line tool
  # get the encrypted variable names from travis cli: https://docs.travis-ci.com/user/encrypting-files/
  - openssl aes-256-cbc -K $encrypted_e82afbcd63e2_key -iv $encrypted_e82afbcd63e2_iv -in gcloud-service-key.json.enc -out gcloud-service-key.json -d
  - gcloud auth activate-service-account --key-file gcloud-service-key.json
  #ADD YOUR PROJECT ID HERE -- this can be found on the On the Google Cloud Platform Dahsboard under 'Project info'
  - gcloud config set project r-spacex-ai

deploy:
  - provider: script
    script:
      # change FUNCTION_NAME PROJECT and REPO to the values from the cloud console: https://console.cloud.google.com/code/develop. Note function name is from your main file, usualy index.js, the main function exports.FUNCTION_NAME
      - gcloud --quiet beta functions deploy SpaceXFulfillment  --source-url https://source.developers.google.com/p/r-spacex-ai/r/r-SpaceX-AI-google-source-repo --source-path / --source-branch master --trigger-http
      - gcloud beta functions call SpaceXFulfillment --data {"id":"f7d278e9-5794-4aff-880e-836000dc6026","timestamp":"2017-11-18T22:03:10.884Z","lang":"en","result":{"source":"agent","resolvedQuery":"when is the next one","action":"get.launchInformation","actionIncomplete":false,"parameters":{"LaunchOrdinal":"","LaunchPads":"","LaunchQueryParams":"launch_date_local","LaunchTemporal":"next","MissionOutcome":"","Vehicles":""},"contexts":[{"name":"_actions_on_google_","parameters":{},"lifespan":100},{"name":"information-given","parameters":{"LaunchTemporal.original":"next","LaunchPads":"","LaunchOrdinal.original":"","Vehicles.original":"","MissionOutcome":"","LaunchTemporal":"next","LaunchQueryParams":"launch_date_local","MissionOutcome.original":"","LaunchOrdinal":"","LaunchQueryParams.original":"when is","LaunchPads.original":"","Vehicles":""},"lifespan":5},{"name":"global","parameters":{"LaunchTemporal.original":"next","LaunchPads":"","LaunchOrdinal.original":"","Vehicles.original":"","MissionOutcome":"","LaunchTemporal":"next","LaunchQueryParams":"launch_date_local","MissionOutcome.original":"","LaunchOrdinal":"","LaunchQueryParams.original":"when is","LaunchPads.original":"","Vehicles":""},"lifespan":98},{"name":"welcome","parameters":{"LaunchTemporal.original":"next","LaunchPads":"","LaunchOrdinal.original":"","Vehicles.original":"","MissionOutcome":"","LaunchTemporal":"next","LaunchQueryParams":"launch_date_local","MissionOutcome.original":"","LaunchOrdinal":"","LaunchQueryParams.original":"when is","LaunchPads.original":"","Vehicles":""},"lifespan":3},{"name":"launches","parameters":{"LaunchTemporal.original":"next","LaunchPads":"","LaunchOrdinal.original":"","Vehicles.original":"","MissionOutcome":"","LaunchTemporal":"next","LaunchQueryParams":"launch_date_local","MissionOutcome.original":"","LaunchOrdinal":"","LaunchQueryParams.original":"when is","LaunchPads.original":"","Vehicles":""},"lifespan":5}],"metadata":{"intentId":"a2ee538a-1ab4-454e-9ce8-d82521efffe3","webhookUsed":"true","webhookForSlotFillingUsed":"false","webhookResponseTime":2110,"intentName":"launchInformation"},"fulfillment":{"speech":"The launch of ZUMA aboard SpaceX's Falcon 9 from KSC LC 39A is due to take place at Sat, 18 Nov 2017 01:00 GMT. Is there anything else I can help with?","messages":[{"type":0,"speech":"The launch of ZUMA aboard SpaceX's Falcon 9 from KSC LC 39A is due to take place at Sat, 18 Nov 2017 01:00 GMT. Is there anything else I can help with?"}],"data":{"google":{"expect_user_response":true,"no_input_prompts":[],"rich_response":{"items":[{"simple_response":{"text_to_speech":"The launch of ZUMA aboard SpaceX's Falcon 9 from KSC LC 39A is due to take place at Sat, 18 Nov 2017 01:00 GMT. Is there anything else I can help with?","display_text":"The launch of ZUMA aboard SpaceX's Falcon 9 from KSC LC 39A is due to take place at Sat, 18 Nov 2017 01:00 GMT. "}}],"suggestions":[]}}}},"score":1},"status":{"code":200,"errorType":"success","webhookTimedOut":false},"sessionId":"c81da7cf-7e6f-4ffe-b75f-ff51b28fde74"} # NOT working, it would be good to emulate and test the function and then only deploy if successful!
    skip_cleanup: true
    on:
      branch: master
